### ISSUE TITLE
How to set rating through kotlin?

### ISSUE THREAD

**Issue by navdeepkhera04** [CaiJingLong/Android-CustomRatingBar#1]
I set the rating following through code but not working
 ratingbarRTT.setStars(user_data.optInt("rating").toFloat())

**Comment by xaldarof** [comment]
Hi ! you can clone source of library then update setStarts() function. 
   
```
public void setStars(float stars) {
        this.stars = stars * 2;
        checkState();
    }

```

**Comment by navdeepkhera04** [comment]
Thanks for this function
